In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# loading data 
data = pd.read_csv("C:\\Users\\DELL\\Desktop\\assignments\\Company_Data.csv")
data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [3]:
data.loc[data.Sales >=8.5,'sales']= 'high'
data.loc[data.Sales <8.5,'sales']= 'low'

In [4]:
data.drop('Sales',1,inplace=True)

C:\Users\DELL\AppData\Local\Temp/ipykernel_2216/3546655252.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  data.drop('Sales',1,inplace=True)


In [5]:
data.isnull().sum()

CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
sales          0
dtype: int64

In [6]:
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
data['US']= label_encoder.fit_transform(data['US']) 
data['US'].unique() 

array([1, 0])

In [7]:
label_encoder = preprocessing.LabelEncoder() 
data['Urban']= label_encoder.fit_transform(data['Urban']) 

In [8]:
label_encoder = preprocessing.LabelEncoder() 
data['ShelveLoc']= label_encoder.fit_transform(data['ShelveLoc'])

In [9]:
colnames = list(data.columns)
predictors = colnames[0:10]
target = colnames[10]

In [10]:
predictors

['CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Urban',
 'US']

In [11]:
target

'sales'

In [12]:
label_encoder = preprocessing.LabelEncoder() 
data['sales']= label_encoder.fit_transform(data['sales']) 

In [13]:
X = data[predictors]
Y = data[target]

In [14]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=1000,criterion="entropy")

In [15]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=1000, n_jobs=2,
                       oob_score=True)

In [16]:
rf.estimators_

[DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1828166085),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1585871393),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=246204864),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1588656380),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1731610838),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1866655623),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=348948052),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
                        random_state=1796841316),
 DecisionTreeClassifier(criterion='entropy', max_features='auto',
        

In [17]:
rf.classes_

array([0, 1])

In [18]:
rf.n_classes_

2

In [19]:
rf.n_features_

10

In [20]:
rf.n_outputs_

1

In [21]:
data['rf_pred'] = rf.predict(X)

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['sales'],data['rf_pred'])

array([[143,   0],
       [  0, 257]], dtype=int64)

## Now will try with 300 decision tress


In [24]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=2,oob_score=True,n_estimators=300,criterion="entropy")

In [25]:
rf.fit(X,Y)

RandomForestClassifier(criterion='entropy', n_estimators=300, n_jobs=2,
                       oob_score=True)

In [26]:
data['rf_pred2'] = rf.predict(X)

In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(data['sales'],data['rf_pred2'])

array([[143,   0],
       [  0, 257]], dtype=int64)